# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy
from scrapy.loader.processors import MapCompose, TakeFirst, Join, Identity



class Betting_Odds(scrapy.Item):

    match_id = scrapy.Field(output_processor = TakeFirst())
    match_link = scrapy.Field(output_processor = TakeFirst())
    time_added = scrapy.Field(output_processor = TakeFirst())
    pick_a_winner_home = scrapy.Field(output_processor = TakeFirst())
    pick_a_winner_away = scrapy.Field(output_processor = TakeFirst())
    egb_com_home = scrapy.Field(output_processor = TakeFirst())
    egb_com_away = scrapy.Field(output_processor = TakeFirst())
    betway_com_home = scrapy.Field(output_processor = TakeFirst())
    betway_com_away = scrapy.Field(output_processor = TakeFirst())
    loot_bet_home = scrapy.Field(output_processor = TakeFirst())
    loot_bet_away = scrapy.Field(output_processor = TakeFirst())
    gg_bet_home = scrapy.Field(output_processor = TakeFirst())
    gg_bet_away = scrapy.Field(output_processor = TakeFirst())
    bet365_home = scrapy.Field(output_processor = TakeFirst())
    bet365_away = scrapy.Field(output_processor = TakeFirst())
    xbet1_home = scrapy.Field(output_processor = TakeFirst())
    xbet1_away = scrapy.Field(output_processor = TakeFirst())
    pinnacle_esport_home = scrapy.Field(output_processor = TakeFirst())
    pinnacle_esport_away = scrapy.Field(output_processor = TakeFirst())
    buff8_home = scrapy.Field(output_processor = TakeFirst())
    buff8_away = scrapy.Field(output_processor = TakeFirst())
    betsnet_home = scrapy.Field(output_processor = TakeFirst())
    betsnet_away = scrapy.Field(output_processor = TakeFirst())
    unikrn_home = scrapy.Field(output_processor = TakeFirst())
    unikrn_away = scrapy.Field(output_processor = TakeFirst())
    betwinner_home = scrapy.Field(output_processor = TakeFirst())
    betwinner_away = scrapy.Field(output_processor = TakeFirst())
    vulkanbet_home = scrapy.Field(output_processor = TakeFirst())
    vulkanbet_away = scrapy.Field(output_processor = TakeFirst())
    unibet_home = scrapy.Field(output_processor = TakeFirst())
    unibet_away = scrapy.Field(output_processor = TakeFirst())
    sts_home = scrapy.Field(output_processor = TakeFirst())
    sts_away = scrapy.Field(output_processor = TakeFirst())
    cyberbet_home =scrapy.Field(output_processor = TakeFirst())
    cyberbet_away = scrapy.Field(output_processor = TakeFirst())
    dmgbet_home = scrapy.Field(output_processor = TakeFirst())
    dmgbet_away = scrapy.Field(output_processor = TakeFirst())
    luckybox_home = scrapy.Field(output_processor = TakeFirst())
    luckybox_away = scrapy.Field(output_processor = TakeFirst())
    csgo500_home = scrapy.Field(output_processor = TakeFirst())
    csgo500_away = scrapy.Field(output_processor = TakeFirst())
    midnite_home = scrapy.Field(output_processor = TakeFirst())
    midnite_away = scrapy.Field(output_processor = TakeFirst())

class Upcoming_Matches_Data(scrapy.Item):
        home_team_id = scrapy.Field(output_processor = TakeFirst())
        away_team_id = scrapy.Field(output_processor = TakeFirst())
        ht_p1_link = scrapy.Field(output_processor = TakeFirst())
        ht_p2_link = scrapy.Field(output_processor = TakeFirst())
        ht_p3_link = scrapy.Field(output_processor = TakeFirst())
        ht_p4_link = scrapy.Field(output_processor = TakeFirst())
        ht_p5_link = scrapy.Field(output_processor = TakeFirst())
        at_p1_link = scrapy.Field(output_processor = TakeFirst())
        at_p2_link = scrapy.Field(output_processor = TakeFirst())
        at_p3_link = scrapy.Field(output_processor = TakeFirst())
        at_p4_link = scrapy.Field(output_processor = TakeFirst())
        at_p5_link = scrapy.Field(output_processor = TakeFirst())
        ht_p1_id   = scrapy.Field(output_processor = TakeFirst())
        ht_p2_id   = scrapy.Field(output_processor = TakeFirst())
        ht_p3_id   = scrapy.Field(output_processor = TakeFirst())
        ht_p4_id   = scrapy.Field(output_processor = TakeFirst())
        ht_p5_id   = scrapy.Field(output_processor = TakeFirst())
        at_p1_id   = scrapy.Field(output_processor = TakeFirst())
        at_p2_id   = scrapy.Field(output_processor = TakeFirst())
        at_p3_id   = scrapy.Field(output_processor = TakeFirst())
        at_p4_id   = scrapy.Field(output_processor = TakeFirst())
        at_p5_id   = scrapy.Field(output_processor = TakeFirst())
        match_link = scrapy.Field(output_processor = TakeFirst())
        match_id = scrapy.Field(output_processor = TakeFirst())
        match_unix_time= scrapy.Field(output_processor = TakeFirst())
        match_date = scrapy.Field(output_processor = TakeFirst())
        match_time = scrapy.Field(output_processor = TakeFirst())

class Upcoming_matches_links(scrapy.Item):
    match_link = scrapy.Field(output_processor = TakeFirst())
    match_id = scrapy.Field(output_processor = TakeFirst())
    match_timestamp = scrapy.Field(output_processor = TakeFirst())
  
class Matches_Results(scrapy.Item):

    match_date_time = scrapy.Field(output_processor = TakeFirst())
    match_date  = scrapy.Field(output_processor = TakeFirst())
    match_time = scrapy.Field(output_processor = TakeFirst())
    match_id = scrapy.Field(output_processor = TakeFirst())
    match_link = scrapy.Field(output_processor = TakeFirst())
    stats_link = scrapy.Field(output_processor = TakeFirst())
    vote_ban = scrapy.Field(output_processor = Identity())
    maps= scrapy.Field(output_processor = TakeFirst())
    home_team_side= scrapy.Field(output_processor = TakeFirst())
    away_team_side= scrapy.Field(output_processor = TakeFirst())
    home_first_score= scrapy.Field(output_processor = TakeFirst())
    away_first_score= scrapy.Field(output_processor = TakeFirst())
    home_second_score= scrapy.Field(output_processor = TakeFirst())
    away_second_score= scrapy.Field(output_processor = TakeFirst())
    home_team_name= scrapy.Field(output_processor = TakeFirst())
    home_team_country= scrapy.Field(output_processor = TakeFirst())
    home_team_link= scrapy.Field(output_processor = TakeFirst())
    home_team_score= scrapy.Field(output_processor = TakeFirst())
    away_team_name= scrapy.Field(output_processor = TakeFirst())
    away_team_country= scrapy.Field(output_processor = TakeFirst())
    away_team_link= scrapy.Field(output_processor = TakeFirst())
    away_team_score= scrapy.Field(output_processor = TakeFirst())
    match_notes= scrapy.Field(output_processor = Identity())
    match_demo_link= scrapy.Field(output_processor = TakeFirst())
    at_p1_name= scrapy.Field(output_processor = TakeFirst())
    at_p1_link= scrapy.Field(output_processor = TakeFirst())
    at_p1_kills= scrapy.Field(output_processor = TakeFirst())
    at_p1_headshots= scrapy.Field(output_processor = TakeFirst())
    at_p1_asists= scrapy.Field(output_processor = TakeFirst())
    at_p1_deaths= scrapy.Field(output_processor = TakeFirst())
    at_p1_kast= scrapy.Field(output_processor = TakeFirst())
    at_p1_adr= scrapy.Field(output_processor = TakeFirst())
    at_p1_fk_diff= scrapy.Field(output_processor = TakeFirst())
    at_p1_rating20= scrapy.Field(output_processor = TakeFirst())
    at_p2_name= scrapy.Field(output_processor = TakeFirst())
    at_p2_link= scrapy.Field(output_processor = TakeFirst())
    at_p2_kills= scrapy.Field(output_processor = TakeFirst())
    at_p2_headshots= scrapy.Field(output_processor = TakeFirst())
    at_p2_asists= scrapy.Field(output_processor = TakeFirst())
    at_p2_deaths= scrapy.Field(output_processor = TakeFirst())
    at_p2_kast= scrapy.Field(output_processor = TakeFirst())
    at_p2_adr= scrapy.Field(output_processor = TakeFirst())
    at_p2_fk_diff= scrapy.Field(output_processor = TakeFirst())
    at_p2_rating20= scrapy.Field(output_processor = TakeFirst())
    at_p3_name= scrapy.Field(output_processor = TakeFirst())
    at_p3_link= scrapy.Field(output_processor = TakeFirst())
    at_p3_kills= scrapy.Field(output_processor = TakeFirst())
    at_p3_headshots= scrapy.Field(output_processor = TakeFirst())
    at_p3_asists= scrapy.Field(output_processor = TakeFirst())
    at_p3_deaths= scrapy.Field(output_processor = TakeFirst())
    at_p3_kast= scrapy.Field(output_processor = TakeFirst())
    at_p3_adr= scrapy.Field(output_processor = TakeFirst())
    at_p3_fk_diff= scrapy.Field(output_processor = TakeFirst())
    at_p3_rating20= scrapy.Field(output_processor = TakeFirst())
    at_p4_name= scrapy.Field(output_processor = TakeFirst())
    at_p4_link= scrapy.Field(output_processor = TakeFirst())
    at_p4_kills= scrapy.Field(output_processor = TakeFirst())
    at_p4_headshots= scrapy.Field(output_processor = TakeFirst())
    at_p4_asists= scrapy.Field(output_processor = TakeFirst())
    at_p4_deaths= scrapy.Field(output_processor = TakeFirst())
    at_p4_kast= scrapy.Field(output_processor = TakeFirst())
    at_p4_adr= scrapy.Field(output_processor = TakeFirst())
    at_p4_fk_diff= scrapy.Field(output_processor = TakeFirst())
    at_p4_rating20= scrapy.Field(output_processor = TakeFirst())
    at_p5_name= scrapy.Field(output_processor = TakeFirst())
    at_p5_link= scrapy.Field(output_processor = TakeFirst())
    at_p5_kills= scrapy.Field(output_processor = TakeFirst())
    at_p5_headshots= scrapy.Field(output_processor = TakeFirst())
    at_p5_asists= scrapy.Field(output_processor = TakeFirst())
    at_p5_deaths= scrapy.Field(output_processor = TakeFirst())
    at_p5_kast= scrapy.Field(output_processor = TakeFirst())
    at_p5_adr= scrapy.Field(output_processor = TakeFirst())
    at_p5_fk_diff= scrapy.Field(output_processor = TakeFirst())
    at_p5_rating20= scrapy.Field(output_processor = TakeFirst())
    ht_p1_name= scrapy.Field(output_processor = TakeFirst())
    ht_p1_link= scrapy.Field(output_processor = TakeFirst())
    ht_p1_kills= scrapy.Field(output_processor = TakeFirst())
    ht_p1_headshots= scrapy.Field(output_processor = TakeFirst())
    ht_p1_asists= scrapy.Field(output_processor = TakeFirst())
    ht_p1_deaths= scrapy.Field(output_processor = TakeFirst())
    ht_p1_kast= scrapy.Field(output_processor = TakeFirst())
    ht_p1_adr= scrapy.Field(output_processor = TakeFirst())
    ht_p1_fk_diff= scrapy.Field(output_processor = TakeFirst())
    ht_p1_rating20= scrapy.Field(output_processor = TakeFirst())
    ht_p2_name= scrapy.Field(output_processor = TakeFirst())
    ht_p2_link= scrapy.Field(output_processor = TakeFirst())
    ht_p2_kills= scrapy.Field(output_processor = TakeFirst())
    ht_p2_headshots= scrapy.Field(output_processor = TakeFirst())
    ht_p2_asists= scrapy.Field(output_processor = TakeFirst())
    ht_p2_deaths= scrapy.Field(output_processor = TakeFirst())
    ht_p2_kast= scrapy.Field(output_processor = TakeFirst())
    ht_p2_adr= scrapy.Field(output_processor = TakeFirst())
    ht_p2_fk_diff= scrapy.Field(output_processor = TakeFirst())
    ht_p2_rating20= scrapy.Field(output_processor = TakeFirst())
    ht_p3_name= scrapy.Field(output_processor = TakeFirst())
    ht_p3_link= scrapy.Field(output_processor = TakeFirst())
    ht_p3_kills= scrapy.Field(output_processor = TakeFirst())
    ht_p3_headshots= scrapy.Field(output_processor = TakeFirst())
    ht_p3_asists= scrapy.Field(output_processor = TakeFirst())
    ht_p3_deaths= scrapy.Field(output_processor = TakeFirst())
    ht_p3_kast= scrapy.Field(output_processor = TakeFirst())
    ht_p3_adr= scrapy.Field(output_processor = TakeFirst())
    ht_p3_fk_diff= scrapy.Field(output_processor = TakeFirst())
    ht_p3_rating20= scrapy.Field(output_processor = TakeFirst())
    ht_p4_name= scrapy.Field(output_processor = TakeFirst())
    ht_p4_link= scrapy.Field(output_processor = TakeFirst())
    ht_p4_kills= scrapy.Field(output_processor = TakeFirst())
    ht_p4_headshots= scrapy.Field(output_processor = TakeFirst())
    ht_p4_asists= scrapy.Field(output_processor = TakeFirst())
    ht_p4_deaths= scrapy.Field(output_processor = TakeFirst())
    ht_p4_kast= scrapy.Field(output_processor = TakeFirst())
    ht_p4_adr= scrapy.Field(output_processor = TakeFirst())
    ht_p4_fk_diff= scrapy.Field(output_processor = TakeFirst())
    ht_p4_rating20= scrapy.Field(output_processor = TakeFirst())
    ht_p5_name= scrapy.Field(output_processor = TakeFirst())
    ht_p5_link= scrapy.Field(output_processor = TakeFirst())
    ht_p5_kills= scrapy.Field(output_processor = TakeFirst())
    ht_p5_headshots= scrapy.Field(output_processor = TakeFirst())
    ht_p5_asists= scrapy.Field(output_processor = TakeFirst())
    ht_p5_deaths= scrapy.Field(output_processor = TakeFirst())
    ht_p5_kast= scrapy.Field(output_processor = TakeFirst())
    ht_p5_adr= scrapy.Field(output_processor = TakeFirst())
    ht_p5_fk_diff= scrapy.Field(output_processor = TakeFirst())
    ht_p5_rating20= scrapy.Field(output_processor = TakeFirst())
    tournament_link= scrapy.Field(output_processor = TakeFirst())
    home_team_id= scrapy.Field(output_processor = TakeFirst())
    away_team_id= scrapy.Field(output_processor = TakeFirst())
    tournament_id= scrapy.Field(output_processor = TakeFirst())
    home_first_kills= scrapy.Field(output_processor = TakeFirst())
    away_first_kills= scrapy.Field(output_processor = TakeFirst())
    home_clutches_won= scrapy.Field(output_processor = TakeFirst())
    away_clutches_won= scrapy.Field(output_processor = TakeFirst())
    ht_p1_id= scrapy.Field(output_processor = TakeFirst())
    ht_p2_id= scrapy.Field(output_processor = TakeFirst())
    ht_p3_id= scrapy.Field(output_processor = TakeFirst())
    ht_p4_id= scrapy.Field(output_processor = TakeFirst())
    ht_p5_id= scrapy.Field(output_processor = TakeFirst())
    at_p1_id= scrapy.Field(output_processor = TakeFirst())
    at_p2_id= scrapy.Field(output_processor = TakeFirst())
    at_p3_id= scrapy.Field(output_processor = TakeFirst())
    at_p4_id= scrapy.Field(output_processor = TakeFirst())
    at_p5_id= scrapy.Field(output_processor = TakeFirst())